### PR TITLE
Added example of va_args using arm abi

### PR DESCRIPTION
**Pull request by fugiefire**
Requires theos toolchain to be installed and in path.

### CODE REVIEW

**Comment by woachk** [comment]
Hello, GPLv3 so not suitable for this project.

**Comment by fugiefire** [comment]
Fixed.

**Comment by fugiefire** [comment]
@woachk I've updated the license, suitable for merging now?

**Comment by woachk** [comment]
Yeah, it's on the backlog now as an alternative if thunking to be able to directly call the version in pongoOS isn't ready in time. :)

**Comment by fugiefire** [comment]
If you mean calling pongoOS's `printf()`, that's not what this example is for. It's to show how to compile a project using ARMs ABI for variadic arguments in general, not just for `printf()`

**Comment by woachk** [comment]
@fugiefire yeah, with an embedded printf instead of calling the host one.

You should note however that your code sample will not use ARM's ABI (AAPCS) but DarwinPCS instead. There's currently an incompatibility when generating AAPCS code for a Mach-O target in Clang.

**Comment by woachk** [comment]
Hello,

We created https://github.com/checkra1n/pongoModules

Would you accept us adapting this PR to there or would you rather submit it yourself?

Thanks,

**Comment by fugiefire** [comment]
Yeah I'm happy for you to adapt it there.

**Pull request closed without merging**
